feat: 헤더 구현
wonsik3686/wine pull request #78
Opened 2024-09-02 16:34 UTC by ayoooyh

# 작업 분류
- [x] 신규 기능
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 기타

# 작업 개요
- 공용 컴포넌트 헤더 구현

# 작업 상세 내용
- 헤더 구현했습니다.

# 리뷰 요구사항
- 코드 리뷰 부탁드립니다!

# 기타
- 
<img width="686" alt="wine_header" src="https://github.com/user-attachments/assets/de8a27df-cf76-4e86-b56a-0c2ff8a44355">

- Closes #35

2024-09-02 18:30 UTC, choi-youngsun commented on tailwind.config.ts
> +      },
👍

2024-09-02 18:30 UTC, choi-youngsun commented on components/common/header.tsx
> +        style={{ padding: '11px 60px' }}
엇 여기 style이 따로 들어간 이유가 있을까요?!

2024-09-02 18:51 UTC, KorpoQ approved these changes

2024-09-02 18:51 UTC, KorpoQ commented on public/svg/wineWhiteLogo-l.svg
svg는 하나만 export해서 사용하시는 것이 더 나을 것 같습니다!

2024-09-03 08:45 UTC, wonsik3686 requested changes

2024-09-03 08:45 UTC, wonsik3686 commented on components/common/header.tsx
> +export default function header() {
컴포넌트명은 네이밍 컨벤션에 따라서 파스칼 케이스로 작성 부탁드립니다
함수명과 파일명 수정 부탁드립니다 🙂

2024-09-03 13:13 UTC, wonsik3686 commented on components/common/header.tsx
> +        style={{ padding: '11px 60px' }}
style 제거하고 tailwind css 사용하여 반영했습니다

2024-09-03 13:14 UTC, wonsik3686 commented on public/svg/wineWhiteLogo-l.svg
Image 컴포넌트 사용하는 것으로 수정했습니다

2024-09-03 13:14 UTC, wonsik3686 commented on components/common/header.tsx
> +export default function header() {
수정 완료

2024-09-03 13:15 UTC, wonsik3686 approved these changes

2024-09-03 13:16 UTC, merged